version: '3'

networks:
  shared-services:
    external: true

services:
  leetcode:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/application
    networks:
      - shared-services
